---
   
   - name: Create pgpass file
     lineinfile:
         path: /var/lib/pgsql/.pgpass
         line: "*:5432:*:edbrepuser:{{ REPLICATION_USER_PASSWORD }}"
         create: yes
         owner: postgres
         group: postgres
         mode: '0600'
     become: yes

   - name: Stop DB service
     systemd:
        name: postgresql-12
        state: stopped
     become: yes

   - name: Delete data directory
     file:
        path: /var/lib/pgsql/12/data
        state: absent
     become: yes
 
   - name: Take pgbase back-up
     shell: PGPASSWORD="{{ REPLICATION_USER_PASSWORD }}" /usr/pgsql-12/bin/pg_basebackup -R -D /var/lib/pgsql/12/data --host="{{ ip1 }}" --port=5432 --username=edbrepuser
     become: yes

   - name: Change permission of data directory
     file:
       path: /var/lib/pgsql/12/data
       state: directory
       owner: postgres
       group: postgres
       recurse: yes
     become: yes
  
   - name: Modify paramter in postgresql.conf file
     lineinfile:
         path: /var/lib/pgsql/12/data/postgresql.conf
         regexp: "{{item.From}}"
         line: "{{item.To}}"
     with_items:
       - { From: "^#promote_trigger_file = ''", To: "promote_trigger_file = '/var/lib/pgsql/12/data/waltrigger'" }
       - { From: "^#restore_command = ''", To: "restore_command = 'aws s3 cp s3://{{ S3BUCKET }}/%f %p'" }
       - { From: "#recovery_target_timeline = 'latest'", To: "recovery_target_timeline = 'latest'" }
     become: yes


   - name: Modify paramter in postgresql.conf file if synchronous replication
     shell: sed -i "s@#primary_conninfo = ''@primary_conninfo = 'user=edbrepuser password={{ REPLICATION_USER_PASSWORD }} host={{ ip1 }} port=5432 sslmode=prefer sslcompression=0 gssencmode=prefer krbsrvname=postgres target_session_attrs=any application_name=slave3'@g" /var/lib/pgsql/12/data/postgresql.conf
     become: yes
     when: REPLICATION_TYPE == 'synchronous'

   - name: Modify paramter in postgresql.conf file if synchronous replication
     shell: sed -i -e 's/target_session_attrs=any/& application_name=slave3/' /var/lib/pgsql/12/data/postgresql.auto.conf
     become: yes
     when: REPLICATION_TYPE == 'synchronous' 

   - name: Add entry in pg_hba file
     lineinfile:
         path: /var/lib/pgsql/12/data/pg_hba.conf
         line: host replication edbrepuser {{ ip2 }}/32 md5
     become: yes

   - name: Add entry in pg_hba file
     lineinfile:
         path: /var/lib/pgsql/12/data/pg_hba.conf
         line: host replication edbrepuser {{ ip3 }}/32 md5
     become: yes

   - name: Start DB process
     systemd:
        name: postgresql-12
        state: restarted
     become: yes


