---
   
   - name: Create pgpass file
     lineinfile:
         path: /var/lib/pgsql/.pgpass
         line: "*:5432:*:edbrepuser:{{ REPLICATION_USER_PASSWORD }}"
         create: yes
         owner: postgres
         group: postgres
         mode: '0600'
     become: yes

   - name: Stop DB service
     systemd:
        name: postgresql-11
        state: stopped
     become: yes

   - name: Delete data directory
     file:
        path: /var/lib/pgsql/11/data
        state: absent
     become: yes
 
   - name: Take pgbase back-up
     shell: PGPASSWORD="{{ REPLICATION_USER_PASSWORD }}" /usr/pgsql-11/bin/pg_basebackup -R -D /var/lib/pgsql/11/data --host={{ ip1 }} --port=5432 --username=edbrepuser
     become: yes

   - name: Change permission of data directory
     file:
       path: /var/lib/pgsql/11/data
       state: directory
       owner: postgres
       group: postgres
       recurse: yes
     become: yes
  
   - name: Create recovery.conf file
     blockinfile:
         path: /var/lib/pgsql/11/data/recovery.conf
         create: yes
         owner: postgres
         group: postgres
         block: |
           trigger_file = '/var/lib/pgsql/11/data/waltrigger'
           restore_command = 'aws s3 cp s3://{{ S3BUCKET }}/%f %p'
           recovery_target_timeline = 'latest'
     become: yes

   - name: Modify recovery.conf file if replication type synchronous
     shell: sed -i -e 's/target_session_attrs=any/& application_name=slave3/' /var/lib/pgsql/11/data/recovery.conf
     become: yes
     when: REPLICATION_TYPE == 'synchronous' 

   - name: Add entry in pg_hba file
     lineinfile:
         path: /var/lib/pgsql/11/data/pg_hba.conf
         line: host replication edbrepuser {{ ip2 }}/32 md5
     become: yes

   - name: Add entry in pg_hba file
     lineinfile:
         path: /var/lib/pgsql/11/data/pg_hba.conf
         line: host replication edbrepuser {{ ip3 }}/32 md5
     become: yes

   - name: Remove extra lines in file
     shell: sed -i '$ d' /var/lib/pgsql/11/data/postgresql.conf
     become: yes


   - name: Start DB process
     systemd:
        name: postgresql-11
        state: restarted
     become: yes


