---
 - hosts: all

   tasks:

     - name: Whitelist new server in master pg_hba file for epas10 dbengine
       lineinfile:
          path: /var/lib/edb/as10/data/pg_hba.conf
          line: host replication edbrepuser {{NEWSLAVE}}/32 md5
       become: yes
       when: DB_ENGINE == 'epas10' and inventory_hostname != NEWSLAVE
     
     - name: Whitelist new server in master pg_hba file for epas11 dbengine
       lineinfile:
          path: /var/lib/edb/as11/data/pg_hba.conf
          line: host replication edbrepuser {{ NEWSLAVE }}/32 md5
       become: yes
       when: DB_ENGINE == 'epas11' and inventory_hostname != NEWSLAVE 

     - name: Whitelist new server in master pg_hba file for epas10 dbengine
       lineinfile:
          path: /var/lib/edb/as12/data/pg_hba.conf
          line: host replication edbrepuser {{ NEWSLAVE }}/32 md5
       become: yes
       when: DB_ENGINE == 'epas12' and inventory_hostname != NEWSLAVE

     - name: Whitelist new server in master pg_hba file for pg10 dbengine
       lineinfile:
          path: /var/lib/pgsql/10/data/pg_hba.conf
          line: host replication edbrepuser {{ NEWSLAVE }}/32 md5
       become: yes
       when: DB_ENGINE == 'pg10' and inventory_hostname != NEWSLAVE

     - name: Whitelist new server in master pg_hba file for pg11 dbengine
       lineinfile:
          path: /var/lib/pgsql/11/data/pg_hba.conf
          line: host replication edbrepuser {{ NEWSLAVE }}/32 md5
       become: yes
       when: DB_ENGINE == 'pg11' and inventory_hostname != NEWSLAVE
 
     - name: Whitelist new server in master pg_hba file for pg12 dbengine
       lineinfile:
          path: /var/lib/pgsql/12/data/pg_hba.conf
          line: host replication edbrepuser {{ NEWSLAVE }}/32 md5
       become: yes
       when: DB_ENGINE == 'pg12' and inventory_hostname != NEWSLAVE 


     - name: Reload DB service on master
       systemd:
         name: edb-as-10
         state: reloaded
       become: yes
       when: DB_ENGINE == 'epas10' and inventory_hostname != NEWSLAVE
     
     - name: Reload DB service on master
       systemd:
         name: edb-as-11
         state: reloaded
       become: yes
       when: DB_ENGINE == 'epas11' and inventory_hostname != NEWSLAVE
  
     - name: Reload DB service on master
       systemd:
         name: edb-as-12
         state: reloaded
       become: yes
       when: DB_ENGINE == 'epas12' and inventory_hostname != NEWSLAVE
 
     - name: Reload DB service on master
       systemd:
         name: postgresql-10
         state: reloaded
       become: yes
       when: DB_ENGINE == 'pg10' and inventory_hostname != NEWSLAVE

     - name: Reload DB service on master
       systemd:
         name: postgresql-11
         state: reloaded
       become: yes
       when: DB_ENGINE == 'pg11' and inventory_hostname != NEWSLAVE
 
     - name: Reload DB service on master
       systemd:
         name: postgresql-12
         state: reloaded
       become: yes
       when: DB_ENGINE == 'pg12' and inventory_hostname != NEWSLAVE
   
     - name: Configure slave for DBengine pg10
       include: configureslavepg10.yml 
       when: DB_ENGINE == 'pg10' and inventory_hostname == NEWSLAVE
     
     - name: Configure slave for DBengine pg11
       include: configureslavepg11.yml 
       when: DB_ENGINE == 'pg11' and inventory_hostname == NEWSLAVE

     - name: Configure slave for DBengine pg12
       include: configureslavepg12.yml 
       when: DB_ENGINE == 'pg12' and inventory_hostname == NEWSLAVE

     - name: Configure slave for DBengine epas10
       include: configureslaveepas10.yml 
       when: DB_ENGINE == 'epas10' and inventory_hostname == NEWSLAVE
     
     - name: Configure slave for DBengine epas11
       include: configureslaveepas11.yml
       when: DB_ENGINE == 'epas11' and inventory_hostname == NEWSLAVE

     - name: Configure slave for DBengine epas12
       include: configureslaveepas12.yml
       when: DB_ENGINE == 'epas12' and inventory_hostname == NEWSLAVE
  
 - hosts: "{{MASTER}}"
   
   tasks:
    
     - name: Change in postgresql.conf file
       lineinfile:
          path: /var/lib/edb/as10/data/postgresql.conf
          regexp: "^#synchronous_standby_names = .*"
          line: synchronous_standby_names = 'any 1 (slave3)'
       become: yes
       run_once: true
       when: DB_ENGINE == 'epas10' and REPLICATION_TYPE == 'synchronous' and inventory_hostname == MASTER
       
  
     - name: restart service
       systemd:
          name: edb-as-10
          state: restarted
       become: yes
       run_once: true
       when: DB_ENGINE == 'epas10'  and REPLICATION_TYPE == 'synchronous' and inventory_hostname == MASTER

     - name: Change in postgresql.conf file
       lineinfile:
          path: /var/lib/edb/as11/data/postgresql.conf
          regexp: "^#synchronous_standby_names = .*"
          line: synchronous_standby_names = 'any 1 (slave3)'
       become: yes
       run_once: true 
       when: DB_ENGINE == 'epas11' and REPLICATION_TYPE == 'synchronous' and inventory_hostname == MASTER
       
  
     - name: restart service
       systemd:
          name: edb-as-11
          state: restarted
       become: yes
       run_once: true
       when: DB_ENGINE == 'epas11' and REPLICATION_TYPE == 'synchronous' and inventory_hostname == MASTER


     - name: Change in postgresql.conf file
       lineinfile:
          path: /var/lib/edb/as12/data/postgresql.conf
          regexp: "^#synchronous_standby_names = .*"
          line: synchronous_standby_names = 'any 1 (slave3)'
       become: yes
       run_once: true
       when: DB_ENGINE == 'epas12' and REPLICATION_TYPE == 'synchronous' and inventory_hostname == MASTER
       
  
     - name: restart service
       systemd:
          name: edb-as-12
          state: restarted
       become: yes
       run_once: true
       when: DB_ENGINE == 'epas12' and REPLICATION_TYPE == 'synchronous' and inventory_hostname == MASTER

     - name: Change in postgresql.conf file
       lineinfile:
          path: /var/lib/pgsql/10/data/postgresql.conf
          regexp: "^#synchronous_standby_names = .*"
          line: synchronous_standby_names = 'any 1 (slave3)'
       become: yes
       run_once: true
       when: DB_ENGINE == 'pg10' and REPLICATION_TYPE == 'synchronous' and inventory_hostname == MASTER
       
  
     - name: restart service
       systemd:
          name: postgresql-10
          state: restarted
       become: yes
       run_once: true
       when: DB_ENGINE == 'pg10' and REPLICATION_TYPE == 'synchronous' and inventory_hostname == MASTER

     - name: Change in postgresql.conf file 
       lineinfile:
          path: /var/lib/pgsql/11/data/postgresql.conf
          regexp: "^#synchronous_standby_names = .*"
          line: synchronous_standby_names = 'any 1 (slave3)'
       become: yes
       run_once: true
       when: DB_ENGINE == 'pg11' and REPLICATION_TYPE == 'synchronous' and inventory_hostname == MASTER
       
  
     - name: restart service
       systemd:
          name: postgresql-11
          state: restarted
       become: yes
       run_once: true
       when: DB_ENGINE == 'pg11' and REPLICATION_TYPE == 'synchronous' and inventory_hostname == MASTER

     - name: Change in postgresql.conf file
       lineinfile:
          path: /var/lib/pgsql/12/data/postgresql.conf
          regexp: "^#synchronous_standby_names = .*"
          line: synchronous_standby_names = 'any 1 (slave3)'
       become: yes
       run_once: true
       when: DB_ENGINE == 'pg12' and REPLICATION_TYPE == 'synchronous' and inventory_hostname == MASTER
       
  
     - name: restart service
       systemd:
          name: postgresql-12
          state: restarted
       become: yes
       run_once: true
       when: DB_ENGINE == 'pg12' and REPLICATION_TYPE == 'synchronous' and inventory_hostname == MASTER     
